version: "3"
services:
  rogrow-backend:
    build:
      context: ./server
      dockerfile: ./DOCKERFILE
    ports:
      - 25030:25030
    networks:
      - default
  rogrow-frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - default
  rogrow-db:
    build:
      context: ./database
      dockerfile: ./DOCKERFILE
    ports:
      - 25031:25031
    networks:
      - default

networks:
  default:
    driver: bridge
