version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: ./DOCKERFILE.production
    ports:
      - 25030:25030
    networks:
      - default
  frontend:
    build:
      context: ./client
      dockerfile: ./DOCKERFILE.production
    ports:
      - 3000:5000
    networks:
      - default
  db:
    build:
      context: ./database
      dockerfile: ./DOCKERFILE.production
    ports:
      - 25031:25031
    networks:
      - default

networks:
  default:
    driver: bridge
